---
apiVersion: v1
kind: Namespace
metadata:
  name: express
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: express
  labels:
    app: olivetask
spec:
  replicas: 5
  selector:
    matchLabels:
      app: olivetask
  template:
    metadata:
      labels:
        app: olivetask
    spec:
      containers:
      - name: olivetask
        image: nginx
        #env:
        #- name: MYSQL_ROOT_PASSWORD
        #  value: "test1234"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: express
spec:
  selector:
    app: olivetask
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
